server:
  port: 8080
  servlet:
    context-path: /api
spring:
  data:
    mongodb:
      uri: ${MONGO_URI}
jwt:
  signerKey: ${SIGNER_KEY}
  valid-duration: 200000 #seconds
  refreshable-duration: 1200000 #seconds